### ISSUE TITLE
Unable to run ncspot 0.13.4

### ISSUE THREAD

**Issue by pesader** [flathub/io.github.hrkfdn.ncspot#12]
When I run the command line:

```bash
flatpak run io.github.hrkfdn.ncspot
```

It fails silently with exit code `25856`. I tried to get some logs by running:

```bash
flatpak run io.github.hrkfdn.ncspot --debug debug.log
```

But it seems to fail before it can even output that. Only the `--version` and `--help` subcommands are working.

**Comment by thorpelawrence** [comment]
I wasn't able to reproduce this, were you able to log in or is this straight after installing?

**Comment by pesader** [comment]
Hey, thank you for the quick response :D

I had it installed for a while, then this started happening. I tried re-installing after running `flatpak uninstall io.github.hrkfdn.ncspot  --delete-data` but that didn't fix the issue.

**Comment by pesader** [comment]
Is there some cache data outside of the flatpak? I can try to clean that too.

**Comment by thorpelawrence** [comment]
Sorry I don't recall where the cache is stored. Please let me know if you remove it and it solves the problem, though.

**Comment by pesader** [comment]
I installed ncspot using cargo, ran it and logged in. After that, the flatpak started working again for some reason. Maybe it accidentally fixed something? 😆

Anyways, thank you for your attention. I'm glad this was just a problem on my end after all.
