### ISSUE TITLE
MPRIS does not work by default

### ISSUE THREAD

**Issue by ghost** [flathub/io.github.hrkfdn.ncspot#37]
After installing the ncspot Flatpak, I do not see any playback information in GNOME Shell or with `playerctl`.

When I add an override for `org.mpris.MediaPlayer2.ncspot.*=own` it does however work fine.

**Comment by thorpelawrence** [comment]
Hey, sorry I haven't had much time to maintain this. But please feel free to submit any changes if it fixed it for you
